Translate docs/tutorial/part five
gatsbyjs/gatsby-ko pull request #11
Opened 2020-02-07 04:31 UTC by vaporwavy

I translated part-five. Thank you for your review!

2020-02-15 16:31 UTC, idpokute requested changes

2020-02-15 16:31 UTC, idpokute commented on docs/tutorial/part-five/index.md
> +여러분은 사이트의 개발서버가 정상 작동 중일 때 다음으로 액세스할 수 있습니다.
여러분의 사이트의 개발 서버가 정상 작동 중이라면 다음의 주소를 통해 GraphiQL에 접속할 수 있습니다.

2020-02-15 16:31 UTC, idpokute commented on docs/tutorial/part-five/index.md
> +먼저, 프로젝트의 루트에 플러그인을 인스톨합니다:
먼저, 프로젝트의 루트에 플러그인을 설치합니다:

2020-02-15 16:31 UTC, idpokute commented on docs/tutorial/part-five/index.md
> +만들어진 `allFile` GraphQL 쿼리를 사용하여 `src/pages/my-files.js`에 새 파일을 만듭니다:
"`src/pages/my-files.js`에 새 파일을 만들고 `allFile` GraphQL 쿼리를 사용해봅시다." 가 어떨까요? 현재 문장은 GraphQL 쿼리 명령어를 사용하면 파일도 만들수 있다는 것같은 늬앙스가 느껴집니다.

2020-02-17 00:41 UTC, vaporwavy commented on docs/tutorial/part-five/index.md
> +만들어진 `allFile` GraphQL 쿼리를 사용하여 `src/pages/my-files.js`에 새 파일을 만듭니다:
아 진짜 그렇게 들리네요. 감사합니다.
```suggestion
`src/pages/my-files.js`에 새 파일을 만들고 아래의 `allFile` GraphQL 쿼리를 사용해봅시다:
```
이렇게 고치도록 하겠습니다!

2020-02-17 00:51 UTC, vaporwavy commented on docs/tutorial/part-five/index.md
> +여러분은 사이트의 개발서버가 정상 작동 중일 때 다음으로 액세스할 수 있습니다.
반영하여 커밋했습니다. 감사합니다!

2020-02-17 00:51 UTC, vaporwavy commented on docs/tutorial/part-five/index.md
> +먼저, 프로젝트의 루트에 플러그인을 인스톨합니다:
반영하여 커밋했습니다. 감사합니다!

2020-02-17 13:33 UTC, idpokute approved these changes

2020-02-17 13:33 UTC, idpokute commented
수고하셨습니다.

2020-02-17 13:33 UTC, merged