Docs/tutorial/part four
gatsbyjs/gatsby-ko pull request #12
Opened 2020-02-15 10:36 UTC by idpokute

파트 4에서는 GraphQL을 어떻게 Gatsby에서 불러오는지에 대한 간단한 입문글이었네요.

2020-02-17 01:52 UTC, weensy requested changes

2020-02-17 01:52 UTC, vaporwavy commented on docs/tutorial/part-four/index.md
> +이번 튜토리알을 포함한 다음 4 파트의 튜토리얼에서, 마크다운, 워드프레스, headless CMS, 그 외의 다양한 데이터 소스로부터 여러분의 사이트를 손쉽게 만들수 있게 해주는 Gatsby의 강력한 특성인 Gatsby 데이터 레이어에 대해서 알아볼 것입니다.
```suggestion
이번 튜토리얼을 포함한 다음 4 파트의 튜토리얼에서, 마크다운, 워드프레스, headless CMS, 그 외의 다양한 데이터 소스로부터 여러분의 사이트를 손쉽게 만들수 있게 해주는 Gatsby의 강력한 특성인 Gatsby 데이터 레이어에 대해서 알아볼 것입니다.
```

2020-02-17 01:52 UTC, vaporwavy commented on docs/tutorial/part-four/index.md
> +**NOTE:** Gatsby 데이터 레이어는 GraphQL에 의해 작동합니다. GraphQL에 더 자세한 내용을 알고 싶다면, [GraphQL의 사용법](https://www.howtographql.com/)을 보기를 권장합니다.
문장이 조금 더 자연스러워 지는 것  같기도 해서 제안해봅니다!
```suggestion
**NOTE:** Gatsby 데이터 레이어는 GraphQL에 의해 작동합니다. GraphQL에 더 자세한 내용을 알고 싶다면, [GraphQL의 사용법](https://www.howtographql.com/)을 보는 것을 권장합니다.
```

2020-02-17 01:52 UTC, vaporwavy commented on docs/tutorial/part-four/index.md
> +컴퓨터 사이언스 측면에서 데이터란 `"문자열"`, 정수 (`42`), 객체 (`{ pizza: true `) 같은 것들입니다.
```suggestion
컴퓨터 사이언스 측면에서 데이터란 `"문자열"`, 정수 (`42`), 객체 (`{ pizza: true }`) 같은 것들입니다.
```

2020-02-17 01:52 UTC, vaporwavy commented on docs/tutorial/part-four/index.md
> +사이트를 만드는데 _훌륭한_ 방법입니다. 하지만 데이터를 컴포넌트 _밖_에 저장한 후 컴포넌트 _안_에 불러와야하는 경우가 자주 있습니다.
만드는 훌륭한 방법은 어떨까요?
```suggestion
사이트를 만드는 _훌륭한_ 방법입니다. 하지만 데이터를 컴포넌트 _밖_에 저장한 후 컴포넌트 _안_에 불러와야하는 경우가 자주 있습니다.
```

2020-02-17 01:52 UTC, vaporwavy commented on docs/tutorial/part-four/index.md
> +**Gatsby의 데이터 레이어는 여러분이 데이터를 직접적으로 컴포넌트에 여러분이 원하는 형태로 가져올 수 있게 해줍니다.
```suggestion
**Gatsby의 데이터 레이어는 여러분이 데이터를 직접적으로 컴포넌트에 여러분이 원하는 형태로 가져올 수 있게 해줍니다.**
```

2020-02-19 07:17 UTC, weensy submitted a review, later dismissed

2020-02-19 07:17 UTC, vaporwavy commented on docs/tutorial/part-four/index.md
> +하지만 Gatsby를 사용하기위한 측면에서 바라본 더욱 유용한 답변은 "React 컴포넌트 밖에 사는 모든 것" 입니다.
약간 오해의 소지가 있을 수도 있을 것 같은데 '있는'은 어떨까요?
```suggestion
하지만 Gatsby를 사용하기위한 측면에서 바라본 더욱 유용한 답변은 "React 컴포넌트 밖에 있는 모든 것" 입니다.
```

2020-02-26 01:03 UTC, idpokute commented on docs/tutorial/part-four/index.md
> +하지만 Gatsby를 사용하기위한 측면에서 바라본 더욱 유용한 답변은 "React 컴포넌트 밖에 사는 모든 것" 입니다.
이 부분은 '있는'이라고 하려다가 원문의 'live'라고 한 의도를 제가 파악하기 힘들어서 직역했었습니다. 글쓴이의 'live'를 그냥 쓴건지 아니면 무슨 의도가 있는지 모르겠네요. 어떻게 생각하시나요?

2020-02-26 02:39 UTC, vaporwavy commented on docs/tutorial/part-four/index.md
> +하지만 Gatsby를 사용하기위한 측면에서 바라본 더욱 유용한 답변은 "React 컴포넌트 밖에 사는 모든 것" 입니다.
저는 "string, integer, object 같은 것들이 아닌, React 컴포넌트 외부의 살아 있는 모든 것!" 처럼
앞의 컴퓨터 사이언스 측면에서의 데이터의 딱딱한 느낌과 대비를 주기위해 live를 썼다고 생각했습니다.
실제 글쓴이의 의도가 어떨지는 모르겠네요..ㅜㅜ

2020-02-26 04:34 UTC, vaporwavy commented on docs/tutorial/part-four/index.md
> +이번 튜토리얼을 포함한 다음 4 파트의 튜토리얼에서, 마크다운, 워드프레스, headless CMS, 그 외의 다양한 데이터 소스로부터 여러분의 사이트를 손쉽게 만들수 있게 해주는 Gatsby의 강력한 특성인 Gatsby 데이터 레이어에 대해서 알아볼 것입니다.
약간 '파트 4'에서라고 오해할 수도 있을 것 같아서 제안드립니다!
```suggestion
이번 튜토리얼을 포함한 네개의 튜토리얼 파트에서, 마크다운, 워드프레스, headless CMS, 그 외의 다양한 데이터 소스로부터 여러분의 사이트를 손쉽게 만들수 있게 해주는 Gatsby의 강력한 특성인 Gatsby 데이터 레이어에 대해서 알아볼 것입니다.
```

2020-05-29 01:59 UTC, idpokute commented on docs/tutorial/part-four/index.md
> +이번 튜토리얼을 포함한 다음 4 파트의 튜토리얼에서, 마크다운, 워드프레스, headless CMS, 그 외의 다양한 데이터 소스로부터 여러분의 사이트를 손쉽게 만들수 있게 해주는 Gatsby의 강력한 특성인 Gatsby 데이터 레이어에 대해서 알아볼 것입니다.
수정이 되었습니다.

2025-01-20 16:36 UTC, closed without merging