transalted page add-404-page.md
gatsbyjs/gatsby-ko pull request #13
Opened 2020-02-16 15:00 UTC by spielers

review and merge this

2020-02-17 01:19 UTC, weensy requested changes

2020-02-17 01:19 UTC, vaporwavy commented on docs/docs/add-404-page.md
> +Gatsby는 404 페이지가 많은 정적 호스팅만큼 `404.html`로 빌드되도록합니다.
```suggestion
Gatsby는 많은 정적 호스팅 플랫폼들이 404 에러 페이지를 기본으로 사용하는 것과 같이, 여러분의 404 페이지를 `404.html`로 빌드해줍니다.
```

2020-02-17 01:19 UTC, vaporwavy commented on docs/docs/add-404-page.md
> +플랫폼은 기본적으로 이것을 404 오류 페이지로 사용합니다 Gatsby는 404 페이지입니다.
```suggestion
다른 방법으로 사이트를 호스팅하는 경우 404 에러에 대해 파일을 제공하도록 커스텀 룰을 설정해야합니다.
```

2020-02-17 01:19 UTC, vaporwavy commented on docs/docs/add-404-page.md
> +플랫폼은 기본적으로 404 오류 페이지로 사용합니다.
```suggestion
```

2020-02-17 01:19 UTC, vaporwavy commented on docs/docs/add-404-page.md
> +Gatsby는 기본적으로이 페이지를 생성하므로 구성 할 필요가 없습니다.
```suggestion
Gatsby는 기본적으로 이 페이지를 만들기 때문에 `gatsby-node.js` 파일에서 해당 페이지를 구성할 필요가 없습니다.
```

2020-02-17 01:19 UTC, vaporwavy commented on docs/docs/add-404-page.md
> +`gatsby-node.js` 파일에 있습니다.
```suggestion
```

2020-02-17 01:19 UTC, vaporwavy commented on docs/docs/add-404-page.md
> +title: 404 페이지 추가
```suggestion
title: 404 페이지 추가하기
```

2020-02-17 01:19 UTC, vaporwavy commented on docs/docs/add-404-page.md
> +404 페이지를 만들려면 경로가 정규식과 일치하는 페이지를 만드십시오.
```suggestion
404 페이지를 만들기 위해서는 경로가 `^\/?404\/?$` (`/404/`, `/404`, `404/` or `404`) 정규식과 일치하는 페이지를 만들어야합니다.
```

2020-02-17 01:19 UTC, vaporwavy commented on docs/docs/add-404-page.md
> +`^\/?404\/?$` (`/404/`, `/404`, `404/` or `404`).대부분의 경우 React 컴포넌트 페이지를 작성하려고합니다.
```suggestion
대부분의 경우 `src / pages / 404.js`에 React 컴포넌트 페이지를 만들고 싶을 것입니다.
```

2020-02-17 01:19 UTC, vaporwavy commented on docs/docs/add-404-page.md
>  `src/pages/404.js`.
```suggestion
```

2020-02-17 02:45 UTC, vaporwavy commented on docs/docs/add-404-page.md
> +`gatsby develop`을 사용하여 개발할 때 Gatsby는 기본 404 페이지를 사용합니다.
`gatsby develop`을 사용하여 개발할 때, Gatsby는 커스텀 404 페이지를 대체해 기본 404 페이지를 사용합니다.

2020-02-17 02:53 UTC, weensy requested changes

2020-02-17 02:53 UTC, vaporwavy commented on docs/docs/add-404-page.md
> +사용자 정의 404 페이지를 대체합니다. 그러나 여전히 404 페이지를 미리 볼 수 있습니다
```suggestion
그러나 "커스텀 404 페이지 미리보기"를 클릭하여 404 페이지를 미리보고, 작동하는지 확인할 수 있습니다.
```

2020-02-17 02:53 UTC, vaporwavy commented on docs/docs/add-404-page.md
> +사용 가능한 모든 페이지를 볼 수 있도록 개발할 때 유용합니다.
```suggestion
이것은 유효한 모든 페이지를 볼 수 있으며, 여러분이 개발 중일 때 유용할 것입니다.
```

2020-02-17 02:53 UTC, vaporwavy commented on docs/docs/add-404-page.md
> +'맞춤형 404 페이지 미리보기'를 클릭하여 예상대로 작동하는지 확인합니다. 이것은
```suggestion
```

2020-02-17 08:50 UTC, spielers commented
fixed the errors please merge this

2020-02-18 08:56 UTC, spielers commented
please merge this

2020-02-23 12:10 UTC, kimdhoe requested changes

2020-02-23 12:10 UTC, kimdhoe commented on docs/docs/add-404-page.md
> +`gatsby develop`을 사용하여 개발할 때, Gatsby는 커스텀 404 페이지를 대체해 기본 404 페이지를 사용합니다.
```suggestion
`gatsby develop`을 사용하여 개발할 때, Gatsby는 커스텀 404 페이지를 대체해 기본 404 페이지를 사용합니다. 하지만 "Preview custom 404 page"를 클릭해서 여러분의 404 페이지가 제대로 작동하는지 확인하기 위해 미리 보는 것이 가능합니다. 이는 여러분이 개발 중에 모든 페이지를 봐야 할 때 유용합니다.
```

2020-02-23 12:10 UTC, kimdhoe commented on docs/docs/add-404-page.md
> +페이지 "버튼을 사용하면 생성 한 404 페이지를 볼 수 있습니다.
불필요하게 중복된 문장과 간격이 들어가 있고 빠진 문장이 있습니다.

> 아래 스크린샷은  Gatsby가 생성하는 기본 404 페이지를 보여줍니다. 또한 웹 사이트의 모든 페이지를 나열합니다. "Preview custom 404 page" 버튼을 클릭하면 여러분이 만든 404 페이지를 볼 수 있습니다.

2020-09-19 07:40 UTC, closed without merging