Translate tutorial/part-six/index.md into Korean
gatsbyjs/gatsby-ko pull request #14
Opened 2020-02-17 12:20 UTC by jongwooo

- 파트 6에 대한 초안을 작성해보았습니다.

- 177, 178번째 줄의 두 문장은 번역을 못했는데, 좋은 의견주시면 참고하겠습니다.

- 변경사항 요청해주시면 바로 적용하겠습니다.

2020-02-17 13:27 UTC, idpokute commented on docs/tutorial/part-six/index.md
> +> 이 튜토리얼은 Gatsby의 데이터 계층의 일부입니다. 이 단계를 진행하기 전에 [파트 4](/tutorial/part-four/)와 [파트 5](/tutorial/part-five/)를 완료했는지 확인해주세요.
이 튜토리얼은 Gatsby 데이터 레이어 시리즈 중 하나입니다. 정도가 어떨까요?

2020-02-17 13:32 UTC, jongwooo commented on docs/tutorial/part-six/index.md
> +> 이 튜토리얼은 Gatsby의 데이터 계층의 일부입니다. 이 단계를 진행하기 전에 [파트 4](/tutorial/part-four/)와 [파트 5](/tutorial/part-five/)를 완료했는지 확인해주세요.
@idpokute 네 변경하도록 하겠습니다!

2020-02-18 09:06 UTC, vaporwavy commented on docs/tutorial/part-six/index.md
> +## `src/pages/index.js`에서 당신의 사이트의 마크다운 파일의 리스트를 만드세요
'당신'을 '여러분'으로 바꾸고 '의'가 한 문장에 세번 나와서
```suggestion
## `src/pages/index.js`안에 사이트의 마크다운 파일 리스트 만들기
```
라는 소제목으로 만들어 봤는데 이건 어떨까요?

2020-02-18 11:27 UTC, jongwooo commented on docs/tutorial/part-six/index.md
> +## `src/pages/index.js`에서 당신의 사이트의 마크다운 파일의 리스트를 만드세요
@vaporwavy 좋은 지적 감사합니다! 변경하도록 하겠습니다!

2020-02-21 00:51 UTC, weensy requested changes

2020-02-21 00:51 UTC, vaporwavy commented on docs/tutorial/part-six/index.md
> +좋습니다! 기초적인 것들이 앞뒤가 맞아가고 있습니다. source 플러그인들은 Gatsby의 데이터 시스템 안으로 데이터를 가져오고 transformer 플러그인들은 source 플러그인이 가져온 가공되지 않은 컨텐츠를 변환합니다. 이 패턴은 여러분이 Gatsby 사이트를 만들때 필요할 모든 데이터 소싱과 데이터 변환을 처리할 수 있습니다.
```suggestion
좋습니다! 기본적인 것들은 잘 맞아들어가고 있어요. source 플러그인들은 Gatsby의 데이터 시스템 안으로 데이터를 가져오고 transformer 플러그인들은 source 플러그인이 가져온 가공되지 않은 컨텐츠를 변환합니다. 이 패턴은 여러분이 Gatsby 사이트를 만들때 필요할 모든 데이터 소싱과 데이터 변환을 처리할 수 있습니다. 
```
조금 부드럽게 바꿔봤는데 어떨까요?

2020-02-21 00:51 UTC, vaporwavy commented on docs/tutorial/part-six/index.md
> +하지만 당신의 한 블로그 포스트는 좀 외로워 보이네요 그러니 `src/pages/pandas-and-bananas.md`에 하나를 추가해봅시다.
```suggestion
하지만 블로그 포스트 하나는 좀 허전해 보이네요. 그러니 `src/pages/pandas-and-bananas.md`에 하나를 추가해봅시다. 
```

2020-02-21 00:51 UTC, vaporwavy commented on docs/tutorial/part-six/index.md
> +하지만 이것은 쉽게 고칠 수 있습니다. 어떠한 유형의 연결을 요청할 때는, 다양한 인자를 GraphQL 쿼리로 넘길 수 있습니다. 여러분은 노드를 `정렬`하고 `걸러낼 수` 있고, 몇개의 노드를 `건너뛸지` 설정할 수 있으며, 몇개의 노드를 검색할지 `한계`를 정할수도 있습니다. 이 강력한 연산자와 함께, 여러분은 여러분이 필요한 포맷으로 여러분이 필요한
```suggestion
하지만 이것은 쉽게 고칠 수 있습니다. 어떠한 유형의 연결을 요청할 때는, 다양한 인자를 GraphQL 쿼리로 넘길 수 있습니다. 여러분은 노드를 `정렬`하고 `걸러낼 수` 있고, 몇개의 노드를 `건너뛸지` 설정할 수 있으며, 몇개의 노드를 검색할지 `제한`을 정할수도 있습니다. 이 강력한 연산자와 함께, 여러분은 여러분이 필요한 포맷으로 여러분이 필요한 데이터를 선택할 수 있습니다.
```

2020-02-21 00:51 UTC, vaporwavy commented on docs/tutorial/part-six/index.md
> +블로그 포스트를 포함한 새로운 페이지를 만드는걸 시도해보고 홈페이지에 있는 블로그 포스트 리스트에 어떤 일이 일어나는지 보세요!
```suggestion
블로그 포스트를 포함한 새로운 페이지를 만들어보고 홈페이지에 있는 블로그 포스트 리스트에 어떤 일이 일어나는지 보세요!
```

2020-02-21 03:20 UTC, jongwooo commented on docs/tutorial/part-six/index.md
> +좋습니다! 기초적인 것들이 앞뒤가 맞아가고 있습니다. source 플러그인들은 Gatsby의 데이터 시스템 안으로 데이터를 가져오고 transformer 플러그인들은 source 플러그인이 가져온 가공되지 않은 컨텐츠를 변환합니다. 이 패턴은 여러분이 Gatsby 사이트를 만들때 필요할 모든 데이터 소싱과 데이터 변환을 처리할 수 있습니다.
@vaporwavy 훨씬 더 깔끔해진 것 같아요! 바로 적용하도록 하겠습니다:)

2020-02-21 07:52 UTC, weensy requested changes

2020-02-21 07:52 UTC, vaporwavy commented on docs/tutorial/part-six/index.md
> +이전 튜토리얼에서는 source 플러그인이 데이터를 Gatsby의 데이터 시스템 내부로 넣는지 보여주었습니다. 이 튜토리얼에서는, 여러분은 transformer 플러그인이 source 플러그인으로부터 가져온 가공되지 않은 내용물을 변환시키는지 배울 것입니다. source 플러그인과 transformer 플러그인의 결합은 Gatsby 사이트를 만들 때 필요
```suggestion
이전 튜토리얼에서는 source 플러그인이 어떻게 데이터를 Gatsby의 데이터 시스템 내부로 넣는지 알아보았습니다. 이번 튜토리얼에서는, 여러분은 transformer 플러그인이 source 플러그인으로부터 가져온 가공되지 않은 내용물을 변환시키는지 배울 것입니다. source 플러그인과 transformer 플러그인의 조합은 Gatsby 사이트를 만들 때 필요할 수 있는 모든 데이터 소싱과 데이터 변환을 처리할 수 있습니다.
```

2020-02-21 07:52 UTC, vaporwavy commented on docs/tutorial/part-six/index.md
> +종종, 여러분이 source 플러그인으로부터 받는 데이터의 형식은 여러분이 자신의 웹사이트를 만드는데 필요한 것이 아닙니다. filesystem source 플러그인은 여러분이 파일에 대한 데이터에 대해 의문을 제기할 수 있게 해주지만 하지만 파일 안에 있는 데이터는 어떻게 해야 할까요?
```suggestion
종종, 여러분이 source 플러그인으로부터 받아오는 데이터의 형식은 여러분이 웹사이트를 만드는데 사용하기위해 원했던 형식이 아닐겁니다. filesystem source 플러그인은 여러분이 파일에 _대한_ 데이터를 쿼리해주지만 파일 _안에_ 있는 데이터는 어떻게 해야 할까요?
```

2020-02-29 09:04 UTC, idpokute approved these changes

2020-02-29 09:05 UTC, idpokute commented
일단 Approval을 하였습니다. 수고하셨습니다.

2022-07-24 13:11 UTC, closed without merging