Translate docs/quick-start.md into Korean
gatsbyjs/gatsby-ko pull request #3
Opened 2019-11-04 12:12 UTC by b6pzeusbc54tvhw5jgpyw8pwz2x6gs

docs/quick-start.md 한국어 번역

## Note
- [ ] production 이란 용어를 프로덕션으로 사용 할까 고민하다가 logLevel 에서의 `debug`, `info` 또는  `NODE_ENV=production` 와 같이 단어 보단 용어로 보는 것이 자연스러워 보여서 `production` 을 그대로 사용 했습니다. 다른분들 의견 부탁드려요.

2019-11-04 13:08 UTC, kimdhoe requested changes

2019-11-04 13:08 UTC, kimdhoe commented on docs/docs/quick-start.md
> +이 빠른 시작은 중급부터 고급 개발자를 위한 가이드 입니다. Gatsby 에 대한 좀 더 쉬운 소개가 필요하면 [튜토리얼을 확인하세요](/tutorial/)!
(띄어쓰기)
```suggestion
이 빠른 시작은 중급부터 고급 개발자를 위한 가이드입니다. Gatsby에 대한 좀 더 쉬운 소개가 필요하면 [튜토리얼을 확인하세요](/tutorial/)!
```

2019-11-04 13:08 UTC, kimdhoe commented on docs/docs/quick-start.md
> +**주의**: 이 영상에서는 npm 패키지를 설치 없이 실행 해주는 도구인 `npx` 를 사용합니다. `npx gatsby new`
(띄어쓰기)
```suggestion
**주의**: 이 영상에서는 npm 패키지를 설치 없이 실행해주는 도구인 `npx`를 사용합니다. `npx gatsby new`
```

2019-11-04 13:08 UTC, kimdhoe commented on docs/docs/quick-start.md
> +명령은 gatsby-cli 를 설치 한 후 `gatsby new` 명령을 실행 하는 것과 동일합니다.
(띄어쓰기)
```suggestion
명령은 gatsby-cli를 설치한 후 `gatsby new` 명령을 실행하는 것과 동일합니다.
```

2019-11-04 13:08 UTC, kimdhoe commented on docs/docs/quick-start.md
> +Gatsby 는 기본 설정으로 `localhost:8000` 을 통해 접근할 수 있는 hot-reloading 개발 서버를 시작할 것입니다.
(띄어쓰기)
```suggestion
Gatsby는 기본 설정으로 `localhost:8000`을 통해 접근할 수 있는 hot-reloading 개발 서버를 시작할 것입니다.
```

2019-11-04 13:08 UTC, kimdhoe commented on docs/docs/quick-start.md
> +Gatsby는 정적 HTML 및 경로 별 JavaScript 코드 번들을 생성하며 사이트에 최적화 된 production 빌드를 수행합니다.
(띄어쓰기)
```suggestion
Gatsby는 정적 HTML 및 경로별 JavaScript 코드 번들을 생성하며 사이트에 최적화된 production 빌드를 수행합니다.
```

2019-11-04 13:08 UTC, kimdhoe commented on docs/docs/quick-start.md
> +Gatsby 는 빌드 된 사이트를 테스트하기 위해 로컬 HTML 서버를 시작합니다. 이 명령어 실행 전 `gatsby build` 를 먼저 해야 한다는 것을 기억하세요.
(띄어쓰기)
```suggestion
Gatsby는 빌드된 사이트를 테스트하기 위해 로컬 HTML 서버를 시작합니다. 이 명령어 실행 전 `gatsby build`를 먼저 해야 한다는 것을 기억하세요.
```

2019-11-04 13:08 UTC, kimdhoe commented on docs/docs/quick-start.md
> +`gatsby --help` 를 실행하면 CLI 명령어에 대한 자세한 문서를 볼 수 있습니다.
(띄어쓰기)
```suggestion
`gatsby --help`를 실행하면 CLI 명령어에 대한 자세한 문서를 볼 수 있습니다.
```

2019-11-04 13:08 UTC, kimdhoe commented on docs/docs/quick-start.md
> +특정 명령어를 위해서는 `gatsby COMMAND_NAME --help` 를 실행하세요. 예. `gatsby new --help`
(띄어쓰기)
```suggestion
특정 명령어를 위해서는 `gatsby COMMAND_NAME --help`를 실행하세요. 예. `gatsby new --help`
```

2019-11-04 13:08 UTC, kimdhoe commented on docs/docs/quick-start.md
> +Gatsby CLI 에 대한 더 자세한 정보는 [CLI 레퍼런스](/docs/gatsby-cli/) 문서를 확인하세요.
(띄어쓰기)
```suggestion
Gatsby CLI에 대한 더 자세한 정보는 [CLI 레퍼런스](/docs/gatsby-cli/) 문서를 확인하세요.
```

2019-11-04 13:08 UTC, kimdhoe commented on docs/docs/quick-start.md
> +Gatsby는 정적 HTML 및 경로 별 JavaScript 코드 번들을 생성하며 사이트에 최적화 된 production 빌드를 수행합니다.
(띄어쓰기)
```suggestion
Gatsby는 정적 HTML 및 경로 별 JavaScript 코드 번들을 생성하며 사이트에 최적화된 production 빌드를 수행합니다.
```

2019-11-04 13:08 UTC, kimdhoe commented on docs/docs/quick-start.md
> +### 로컬 환경에서 production 빌드 서비스.
저라면 여기 _빌드 서비스_라는 표현이 살짝 이해하기 어려울 수도 있을 것 같아요.

2019-11-04 13:11 UTC, kimdhoe commented
_production_ 그대로 두는 건 저도 자연스러워 보입니다.

2019-11-04 13:35 UTC, b6pzeusbc54tvhw5jgpyw8pwz2x6gs commented on docs/docs/quick-start.md
> +### 로컬 환경에서 production 빌드 서비스.
네 동의합니다. 빌드가 동사로도 쓰이고 여기서는 빌드 산출물, 빌드된 파일의 의미로 사용된 거라 어렵네요.

의미는 `production 빌드 후 로컬 환경에서 테스트` 이거인데.. 이정도로 의역을 하면 어떨까요??

2019-11-04 13:38 UTC, b6pzeusbc54tvhw5jgpyw8pwz2x6gs commented
@kimdhoe 영단어 + 한글 조사 일 때 붙여쓰기! 담부터 주의 하겠습니다. 고쳐주셔서 감사합니다. :)

2019-11-04 13:44 UTC, kimdhoe commented on docs/docs/quick-start.md
> +### 로컬 환경에서 production 빌드 서비스.
전 후자가 괜찮아 보이네요. 이해가 잘 갑니다 :)
저도 의역을 너무 두려워하지 않으려고 하는데 역시 적당한 선을 찾는 게 어려운 것 같습니다

2019-11-04 13:46 UTC, b6pzeusbc54tvhw5jgpyw8pwz2x6gs commented on docs/docs/quick-start.md
> +### 로컬 환경에서 production 빌드 서비스.
의견 고맙습니다! 내일 이부분 업뎃하고 커밋들 하나로 squash 해 두겠습니다.
좋은 밤 되세요 :)

2019-11-04 13:48 UTC, kimdhoe commented on docs/docs/quick-start.md
> +### 로컬 환경에서 production 빌드 서비스.
넵, Good night 고생하셨습니다!

2019-11-04 15:38 UTC, kimdhoe submitted a review, later dismissed

2019-11-05 19:42 UTC, woonjangahn submitted a review, later dismissed

2019-11-05 19:42 UTC, woonjangahn commented on docs/docs/quick-start.md
> +### Gatsby CLI 설치.
**Gatsby CLI 설치.** 보단 **Gatsby CLI를 설치하세요.** 또는 **Gatsby CLI 설치**(마침표 제외) 로 변경하는게 낫지않을까요? 다른 소제목들도 마찬가지입니다!

2019-11-08 14:21 UTC, b6pzeusbc54tvhw5jgpyw8pwz2x6gs commented on docs/docs/quick-start.md
> +### Gatsby CLI 설치.
저도 마침표가 있는게 좀 이상하다고 생각하면서 원문에 있으니 그대로 넣었는데 마침표를 제거해도 괜찮다면 `Gatsby CLI 설치(마침표 제외)` 로 일괄 수정하겠습니다.

2019-11-18 18:36 UTC, idpokute approved these changes
술술 잘 읽히네요. 수고하셨습니다.

2019-11-21 13:35 UTC, b6pzeusbc54tvhw5jgpyw8pwz2x6gs commented
@kimdhoe @idpokute @woonjangahn 
머지는 어떻게 진행하고 계신가요? 제가 최종 확인 후 바로 머지 하면 되는 걸까요?

2019-11-21 14:20 UTC, kimdhoe commented
Approve 되면 이후에 다른 논의사항이 있지 않는 한 메인테이너 누구나 머지할 수 있고 해야 하는 걸로 보면 되지 않을까 하는데 어떻게 생각하세요?

2019-11-23 08:38 UTC, b6pzeusbc54tvhw5jgpyw8pwz2x6gs commented
@kimdhoe 네, 괜찮은것 같습니다. 일단 말씀해주신대로 누구나 머지 하고 추후 문제 발생하면 그때 다시 얘기하면 되지 않을까 싶네요!

2019-12-03 11:29 UTC, merged