Translate tutorial/part-zero/index.md into Korean
gatsbyjs/gatsby-ko pull request #5
Opened 2019-11-11 21:23 UTC by woonjangahn

- 일단 전체적으로 초안을 작성했습니다.
- 84번째 줄의 한 문장은 일단 번역을 못했는데, 좋은 의견주시면 참고하겠습니다.
- 다소 길어서 단어 선택이나 번역투에 대한 통일성이 약할 수 있습니다. 변경사항 요청해주시면 바로바로 적용하겠습니다.

2019-11-12 17:09 UTC, idpokute commented
- For brevity's sake, the gif below was paused during part of the install.
- 불필요한 부분은 하지 않으려고하니, gif  부분은 이번 설치 과정에서는 하지 않겠습니다.
- gif 가 뜻하는게 gif 이미지인거 같은데...뜬금없이 왜 gif 를 언급하는걸까요?

영어 잘하시는 분의 조언을 기다립니다.

2019-11-12 17:16 UTC, woonjangahn commented
> * For brevity's sake, the gif below was paused during part of the install.
> * 불필요한 부분은 하지 않으려고하니, gif  부분은 이번 설치 과정에서는 하지 않겠습니다.
> * gif 가 뜻하는게 gif 이미지인거 같은데...뜬금없이 왜 gif 를 언급하는걸까요?
> 
> 영어 잘하시는 분의 조언을 기다립니다.

제가 의역했던 건 **"설명을 위해서 녹화된 아래의 gif 역시 실제 설치 시간보다 짧게 녹화된 것입니다"** 정도로 생각을 했는데 어떻게 생각하시나요?

2019-11-12 17:22 UTC, idpokute commented
듣고보니 그게 맞는거 같아요.

2019-11-15 13:43 UTC, kimdhoe requested changes
오타를 몇 개 찾았습니다 :)

2019-11-15 13:43 UTC, kimdhoe commented on docs/tutorial/part-zero/index.md
> +다음 기술들에 대해 벌써부터 전문적인 지식이 필요하진 않습니다. — 그러니까 혹시 잘 모르겠어도 걱정하지 마세요! 여러분은 이 튜토리얼 시리즈를 거치며 많은 것들을 배우게 될 것입니다. 다음은 여러분들이 Gastby 사이트를 만들며 사용하게 될 몇 가지 웹 기술들입니다:
```suggestion
다음 기술들에 대해 벌써부터 전문적인 지식이 필요하진 않습니다. — 그러니까 혹시 잘 모르겠어도 걱정하지 마세요! 여러분은 이 튜토리얼 시리즈를 거치며 많은 것들을 배우게 될 것입니다. 다음은 여러분들이 Gatsby 사이트를 만들며 사용하게 될 몇 가지 웹 기술들입니다:
```

2019-11-15 13:43 UTC, kimdhoe commented on docs/tutorial/part-zero/index.md
> +- **React**: 사용자 인터페이스를 구축하기 위한 코드 라이브러리로 (JavaScript로 만들어졌습니다) Gastby를 이용해 페이지를 만들고 컨텐츠를 설계하는데 있어 사용됩니다.
```suggestion
- **React**: 사용자 인터페이스를 구축하기 위한 코드 라이브러리로 (JavaScript로 만들어졌습니다) Gatsby를 이용해 페이지를 만들고 컨텐츠를 설계하는데 있어 사용됩니다.
```

2019-11-15 13:43 UTC, kimdhoe commented on docs/tutorial/part-zero/index.md
> +- **GraphQL**: 웹 사이트로 데이터를 가져올 수 있는 쿼리 언어입니다. Gastby를 이용해 사이트의 데이터를 관리하기 위해 사용하는 인터페이스입니다.
```suggestion
- **GraphQL**: 웹 사이트로 데이터를 가져올 수 있는 쿼리 언어입니다. Gatsby를 이용해 사이트의 데이터를 관리하기 위해 사용하는 인터페이스입니다.
```

2019-11-15 13:43 UTC, kimdhoe commented on docs/tutorial/part-zero/index.md
> +2.  `gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world`를 실행하세요. (\_노트: 여러분의 다운로드 속도에 따라 소요 시간이 상이할 수 있습니다. 설명을 위해서 녹화된 아래의 gif 역시 실제 설치 시간보다 짧게 녹화된 것입니다).
```suggestion
2.  `gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world`를 실행하세요. (\_노트: 여러분의 다운로드 속도에 따라 소요 시간이 상이할 수 있습니다. 설명을 위해서 녹화된 아래의 gif 역시 실제 설치 시간보다 짧게 녹화된 것입니다_).
```

2019-11-15 13:52 UTC, kimdhoe commented on docs/tutorial/part-zero/index.md
> +- 마지막 GitHub 주소 부분은 여러분이 설치에 사용하고 있는 스타터의 특정 주소를 가리키고 있습니다.
전 여기 "_스타터의 주소를 가리킨다_"는 말이 모호해서 이해하기가 조금 어려웠습니다.

2019-11-16 01:11 UTC, woonjangahn commented on docs/tutorial/part-zero/index.md
> +다음 기술들에 대해 벌써부터 전문적인 지식이 필요하진 않습니다. — 그러니까 혹시 잘 모르겠어도 걱정하지 마세요! 여러분은 이 튜토리얼 시리즈를 거치며 많은 것들을 배우게 될 것입니다. 다음은 여러분들이 Gastby 사이트를 만들며 사용하게 될 몇 가지 웹 기술들입니다:
수정했습니다. 감사합니다!

2019-11-16 01:11 UTC, woonjangahn commented on docs/tutorial/part-zero/index.md
> +- **React**: 사용자 인터페이스를 구축하기 위한 코드 라이브러리로 (JavaScript로 만들어졌습니다) Gastby를 이용해 페이지를 만들고 컨텐츠를 설계하는데 있어 사용됩니다.
수정했습니다. 감사합니다!

2019-11-16 01:11 UTC, woonjangahn commented on docs/tutorial/part-zero/index.md
> +- **GraphQL**: 웹 사이트로 데이터를 가져올 수 있는 쿼리 언어입니다. Gastby를 이용해 사이트의 데이터를 관리하기 위해 사용하는 인터페이스입니다.
수정했습니다. 감사합니다!

2019-11-16 01:14 UTC, woonjangahn commented on docs/tutorial/part-zero/index.md
> +- 마지막 GitHub 주소 부분은 여러분이 설치에 사용하고 있는 스타터의 특정 주소를 가리키고 있습니다.
흠.. 혹시 "_스타터의 Repository 주소_" 가 나을까요? 다른 좋은 의견 있으시면 참고하겠습니다!

2019-11-16 12:41 UTC, kimdhoe commented on docs/tutorial/part-zero/index.md
> +- 마지막 GitHub 주소 부분은 여러분이 설치에 사용하고 있는 스타터의 특정 주소를 가리키고 있습니다.
그게 쉽게 이해가 되고 좋은 것 같습니다! Repository는 저장소로 많이 번역되는 것 같은데 그렇게 하면 괜찮지 않을까 합니다.

2019-11-16 12:42 UTC, kimdhoe submitted a review, later dismissed

2019-11-16 13:57 UTC, woonjangahn commented on docs/tutorial/part-zero/index.md
> +- 마지막 GitHub 주소 부분은 여러분이 설치에 사용하고 있는 스타터의 특정 주소를 가리키고 있습니다.
네, 수정했습니다. 감사합니다!

2019-11-18 05:44 UTC, kimdhoe approved these changes
LGTM

2019-11-18 18:42 UTC, idpokute commented on docs/tutorial/part-zero/index.md
> +커맨드라인은 여러분의 컴퓨터에서 명령을 실행하는데 사용되는 텍스트 기반 인터페이스입니다. 터미널이라고 부르기도 하죠. 이 튜토리얼에선 두 용어가 같다고 생각하시면 됩니다. Mac에서 Finder를 사용하거나 Windows에서 탐색기를 사용하는 것과 비슷합니다. Finder와 탐색기는 그래픽 기반 인터페이스(Graphical user interfaces,
크리티컬한건 아닌데요. `종종` 터미널이라고 부르기도 하죠. 라고 하면 다음 문장을 보고 예외 적인 경우가 있다고 약간의 암시(?)같은걸 느낄수 있지 않을까 합니다.

2019-11-18 18:48 UTC, idpokute commented on docs/tutorial/part-zero/index.md
> +Gatsby와 Node.js를 설치하기 위해선 [Homebrew](https://brew.sh/)를 사용하시는 것을 추천드립니다. 처음에 해 놓는 설정들이 나중에 여러분들에게 편하게 다가오니까요!
의역이긴한데, `지금하는 약간의 설정이 여러분들이 나중에 만날 골치 덩어리들을 해결해줄 것입니다!` 는 어떨까요?

2019-11-18 18:56 UTC, idpokute commented on docs/tutorial/part-zero/index.md
> +Git은 무료 오픈소스로 배포된 버전 관리 시스템으로 규모가 작거나 큰 모든 프로젝트들을 빠르고 효율적으로 관리할 수 있게 해줍니다. 여러분이 Gatsby "스타터" 사이트를 설치할 때, Gatsby는 실제로는 Git을 사용하여 여러분들의 사이트에 필요한 파일들을 다운로드하고 설치합니다. 여러분의 첫번째 Gatsby 사이트를 만들기 위해서는 Git이 설치
쌍따옴표 안의 내용은 번역하지않고 "starter" 로 놔두면 어떨까요?

2019-11-18 19:15 UTC, idpokute commented
command 는 명령어로 해석하면 어떨까요? 한국의 기술 서적은 `명령어`라고 자주 쓰는 것 같습니다.

2019-11-19 21:28 UTC, idpokute approved these changes
수고하셨습니다.

2019-11-24 14:41 UTC, woonjangahn commented on docs/tutorial/part-zero/index.md
> +Gatsby와 Node.js를 설치하기 위해선 [Homebrew](https://brew.sh/)를 사용하시는 것을 추천드립니다. 처음에 해 놓는 설정들이 나중에 여러분들에게 편하게 다가오니까요!
오 좋아요 훨씬 자연스럽네요!

2019-11-24 14:42 UTC, woonjangahn commented on docs/tutorial/part-zero/index.md
> +커맨드라인은 여러분의 컴퓨터에서 명령을 실행하는데 사용되는 텍스트 기반 인터페이스입니다. 터미널이라고 부르기도 하죠. 이 튜토리얼에선 두 용어가 같다고 생각하시면 됩니다. Mac에서 Finder를 사용하거나 Windows에서 탐색기를 사용하는 것과 비슷합니다. Finder와 탐색기는 그래픽 기반 인터페이스(Graphical user interfaces,
네~ 추가하겠습니다!

2019-12-03 11:31 UTC, merged