워드프레스 플러그인 번역을 해보았습니다.
gatsbyjs/gatsby-ko pull request #6
Opened 2019-11-19 21:26 UTC by idpokute

본업이 워드프레스 개발자다보니 워드프레스 쪽을 먼저 해보았습니다.

2019-11-21 13:33 UTC, b6pzeusbc54tvhw5jgpyw8pwz2x6gs commented
제 분량 하느라 정신이 없어서 자세히 보진 못했는데요,
하나만 말씀드리면 외래어 표기법 상 `튜토리알` 이 아닌 `튜토리얼` 이 맞는 것으로 알고 있습니다.

https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=90113

2019-11-22 01:55 UTC, idpokute commented
> 제 분량 하느라 정신이 없어서 자세히 보진 못했는데요,
> 하나만 말씀드리면 외래어 표기법 상 `튜토리알` 이 아닌 `튜토리얼` 이 맞는 것으로 알고 있습니다.
> 
> https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=90113

감사합니다. 나중에 바꾼다고 했었는데 깜빡했었네요. 튜토리얼로 바꾸었습니다.

2019-11-23 14:14 UTC, kimdhoe requested changes
실수로 원문이 남아있는 거랑 오타 등 몇 개 수정사항을 찾았습니다.

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +이번 튜토리얼에서, 설치된 워드프레스로부터 블로그와 이미지 데이터를 Gatsby 사이트로 가져와서 데이터를 출력하기 위한 `gatsby-source-wordpress` 플러그인을 설치할 것입니다. [Gatsby + WordPress demo site](https://github.com/gatsbyjs/gatsby/tree/master/examples/us
```suggestion
이번 튜토리얼에서, 설치된 워드프레스로부터 블로그와 이미지 데이터를 Gatsby 사이트로 가져와서 데이터를 출력하기 위한 `gatsby-source-wordpress` 플러그인을 설치할 것입니다. [Gatsby + WordPress demo site](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-wordpress) 는 이번 튜토리얼에서 만들 것과 유사한 예제 사이트의 소스 코드를 보여줍니다. 이번 튜토리얼의 다음 파트, [Adding Images to a WordPress Site](/tutorial/wordpress-image-tutorial/)에서 다룰 예정인 멋진 이미지들이 빠져있지만이요. :D
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +각각의 source 플러그인이 작동하는 방법은 다를 수 있지만, 여러분이 앞으로 만들게 될 거의 대부분의 Gtasby 사이트에서 source 플러그인을 사용하게 될 것이기 때문에 이번 튜토리얼을 살펴볼 가치가 있습니다. 이번 튜토리얼에서 여러분은 Gtasby 사이트와 CMS의 기본적인 연결과, 데이터를 가져오고, 그 데이터를 React를 사용해서 여러분의
```suggestion
각각의 source 플러그인이 작동하는 방법은 다를 수 있지만, 여러분이 앞으로 만들게 될 거의 대부분의 Gatsby 사이트에서 source 플러그인을 사용하게 될 것이기 때문에 이번 튜토리얼을 살펴볼 가치가 있습니다. 이번 튜토리얼에서 여러분은 Gatsby 사이트와 CMS의 기본적인 연결과, 데이터를 가져오고, 그 데이터를 React를 사용해서 여러분의 사이트에 우아한 방법으로 출력할 것입니다.
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +        // 프로토콜: http 나 https 입니다.
```suggestion
        // 프로토콜: http나 https입니다.
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +        // wordpress.com 에 의해 호스팅 되는 사이트 인지 아닌지 명시.
```suggestion
        // wordpress.com에 의해 호스팅 되는 사이트 인지 아닌지 명시.
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +        // false 이면, 자체 호스팅되는 사이트라고 판단합니다.
```suggestion
        // false이면, 자체 호스팅되는 사이트라고 판단합니다.
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +        // true 이면, 플러그인은 JSON REST API V2 를 사용해서 wordpress.com의 컨텐츠를 가져옵니다.
```suggestion
        // true이면, 플러그인은 JSON REST API V2를 사용해서 wordpress.com의 컨텐츠를 가져옵니다.
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +        // useACF가 true이면, source 플러그인은 Wordpress ACF 플러그인 컨텐츠를 가져올것입니다.
```suggestion
        // useACF가 true이면, source 플러그인은 Wordpress ACF 플러그인 컨텐츠를 가져올 것입니다.
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +        // 이 기능은 WordPress.com 에서 호스팅되는 사이트는 아직 테스트되지 않았습니다.
```suggestion
        // 이 기능은 WordPress.com에서 호스팅되는 사이트는 아직 테스트되지 않았습니다.
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +브라우저 상에서 localhost:8000 에 접속해서 사이트를 보고, GraphQL 쿼리를 작성할 수 있는 localhost:8000/\_\_\_graphql 도 접속하세요.
```suggestion
브라우저 상에서 localhost:8000에 접속해서 사이트를 보고, GraphQL 쿼리를 작성할 수 있는 localhost:8000/\_\_\_graphql로 접속하세요.
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +이제까지 여러분은 원하는 데이터를 가져오는 GraphQL 쿼리들을 작성했습니다. 두번째 쿼리를 사용해서 여러분의 사이트 홈페이지에 정렬된 블로그의 제목 리스트를 보여주겠습니다. 여러분의 `index.js` 는 다음과 같아야 합니다:
```suggestion
이제까지 여러분은 원하는 데이터를 가져오는 GraphQL 쿼리들을 작성했습니다. 두번째 쿼리를 사용해서 여러분의 사이트 홈페이지에 정렬된 블로그의 제목 리스트를 보여주겠습니다. 여러분의 `index.js`는 다음과 같아야 합니다:
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +import React from "react";
```suggestion
import React from "react"
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +import { graphql } from "gatsby";
```suggestion
import { graphql } from "gatsby"
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +import Layout from "../components/layout";
```suggestion
import Layout from "../components/layout"
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +import SEO from "../components/seo";
```suggestion
import SEO from "../components/seo"
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +  );
```suggestion
  )
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +};
```suggestion
}
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +`;
```suggestion
`
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +바꾼 것들을 저장하고 localhost:8000 에 접속해서, 정렬된 블로그 포스트 목록이 보이는 여러분의 새로운 홈페이지를 보세요.
```suggestion
바꾼 것들을 저장하고 localhost:8000에 접속해서, 정렬된 블로그 포스트 목록이 보이는 여러분의 새로운 홈페이지를 보세요.
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +const path = require(`path`);
```suggestion
const path = require(`path`)
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +  const { createPage } = actions;
```suggestion
  const { createPage } = actions
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +  });
```suggestion
  })
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +};
```suggestion
}
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +import React from "react";
```suggestion
import React from "react"
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +import Layout from "../components/layout";
```suggestion
import Layout from "../components/layout"
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +import { graphql } from "gatsby";
```suggestion
import { graphql } from "gatsby"
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +  console.log(post);
```suggestion
  console.log(post)
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +  const post = data.allWordpressPost.edges[0].node;
```suggestion
  const post = data.allWordpressPost.edges[0].node
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +  console.log(post);
```suggestion
  console.log(post)
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +  );
```suggestion
  )
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +};
```suggestion
}
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +`;
```suggestion
`
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
>  What is this file doing? After importing your dependencies, it constructs the layout of the post with JSX. It wraps everything in the `Layout` component, so the style is the same throughout the site.
```suggestion
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +const path = require(`path`);
```suggestion
const path = require(`path`)
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +  const { createPage } = actions;
```suggestion
  const { createPage } = actions
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +      });
```suggestion
      })
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +  });
```suggestion
  })
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +  });
```suggestion
  })
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +};
```suggestion
}
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +import React from "react";
```suggestion
import React from "react"
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +import { Link, graphql } from "gatsby"; //highlight-line
```suggestion
import { Link, graphql } from "gatsby" //highlight-line
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +import Layout from "../components/layout";
```suggestion
import Layout from "../components/layout"
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +import SEO from "../components/seo";
```suggestion
import SEO from "../components/seo"
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +  );
```suggestion
  )
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +};
```suggestion
}
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +`;
```suggestion
`
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +이게 전부입니다~ `Link` 컴포넌트로 타이틀을 감싸고 포스트의 slug 를 참조하면, Gatsby가 마법과도 같이 link를 추가하고, 미리 로딩하고, 완전 빠르게 페이지 간의 전환을 만들어줍니다:
```suggestion
이게 전부입니다~ `Link` 컴포넌트로 타이틀을 감싸고 포스트의 slug를 참조하면, Gatsby가 마법과도 같이 link를 추가하고, 미리 로딩하고, 완전 빠르게 페이지 간의 전환을 만들어줍니다:
```

2019-11-23 14:14 UTC, kimdhoe commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +여러분은 동일한 절차를 페이지, 커스텀 포스트 타입, 커스텀 필드, 텍사노미 및 WordPress가 알고 있는 모든 유연하고 재미있는 컨텐츠를 호출하거나 생성하는데 적용할 수 있습니다. 이는 여러분이 원하는 만큼 쉬울수도 복잡할 수 있으니, 탐험하고 즐기세요!
```suggestion
여러분은 동일한 절차를 페이지, 커스텀 포스트 타입, 커스텀 필드, 텍사노미 및 WordPress가 알고 있는 모든 유연하고 재미있는 컨텐츠를 호출하거나 생성하는 데 적용할 수 있습니다. 이는 여러분이 원하는 만큼 쉬울 수도 복잡할 수 있으니, 탐험하고 즐기세요!
```

2019-11-23 14:15 UTC, kimdhoe requested changes
실수로 원문이 남아있는 거랑 코드블럭에 원문에 없는 세미콜론이 추가된 것, 오타 등 몇 개 수정사항을 찾았습니다.
이 문서가 양이 많네요. 고생하셨습니다 :)

2019-11-24 13:11 UTC, idpokute commented
> 실수로 원문이 남아있는 거랑 코드블럭에 원문에 없는 세미콜론이 추가된 것, 오타 등 몇 개 수정사항을 찾았습니다.
> 이 문서가 양이 많네요. 고생하셨습니다 :)

vs-extension이 자동으로 세미콜론을 붙인것 같네요. 수정 감사합니다.

2019-11-28 02:36 UTC, idpokute commented on docs/tutorial/wordpress-source-plugin-tutorial.md
> +여러분은 동일한 절차를 페이지, 커스텀 포스트 타입, 커스텀 필드, 텍사노미 및 WordPress가 알고 있는 모든 유연하고 재미있는 컨텐츠를 호출하거나 생성하는데 적용할 수 있습니다. 이는 여러분이 원하는 만큼 쉬울수도 복잡할 수 있으니, 탐험하고 즐기세요!
리뷰 부탁합니다.

2019-12-02 02:41 UTC, idpokute commented
리뷰 바랍니다.

2019-12-02 05:29 UTC, kimdhoe approved these changes

2019-12-03 11:28 UTC, merged