Docs/tutorial/part two
gatsbyjs/gatsby-ko pull request #9
Opened 2020-01-04 01:11 UTC by idpokute

이번엔 파트 2입니다.

2020-01-06 16:23 UTC, kimdhoe requested changes
수고하셨습니다! 오타를 하나 발견했습니다.

2020-01-06 16:23 UTC, kimdhoe commented on docs/tutorial/part-two/index.md
> +Gtasby는 CSS 모듈을 별도의 설치나 설정없이 바로 함께 작동합니다. 이 방법은 Gatsby(그리고 일반적으로 React)를 사용해서 새로 무언가를 만드는 분들에게 매우 권장합니다.
```suggestion
Gatsby는 CSS 모듈을 별도의 설치나 설정없이 바로 함께 작동합니다. 이 방법은 Gatsby(그리고 일반적으로 React)를 사용해서 새로 무언가를 만드는 분들에게 매우 권장합니다.
```

2020-01-06 17:01 UTC, idpokute commented
감사합니다. 방금 수정했어요. 확인 후에 별문제 없으면 Merge 해주세요. @kimdhoe

2020-01-07 00:53 UTC, kimdhoe approved these changes

2020-01-07 00:53 UTC, merged